import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { createPlaylistByMatchingSongs } from './api/spotify-service'
import { getTrackList } from './api/openai-service'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  let matchedflksadf = [] = [];
  createPlaylistByMatchingSongs(matchedflksadf);


// Handles the submit event on form submit.
const handleSubmit = async (event) => {
  // Stop the form from submitting and refreshing the page.
  event.preventDefault()

  // Get data from the form.
  const data = {
    UserInputforms: event.target.UserInputforms.value
    
  }

  // Send the data to the server in JSON format.
  const JSONdata = JSON.stringify(data)

  // API endpoint where we send form data.
  const endpoint = '/api/form'

  // Form the request for sending data to the server.
  const options = {
    // The method is POST because we are sending data.
    method: 'POST',
    // Tell the server we're sending JSON.
    headers: {
      'Content-Type': 'application/json',
    },
    // Body of the request is the JSON data we created above.
    body: JSONdata,
  }

  // Send the form data to our forms API on Vercel and get a response.
  const response = await fetch(endpoint, options)

  // Get the response data from server as JSON.
  // If server returns the name submitted, that means the form works.
  const result = await response.json()


  getTrackList(event.target.UserInputforms.value);

}

  return (
    <>
      <Head>
        <title>Platify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
        
          <form onSubmit={handleSubmit}>
            <label htmlFor="UserInputforms">Playlist Tags</label>
            <input type="text" id='UserInputforms' name='UserInputforms' />

            <button type='submit'>Submit</button>
          </form>
          

          <div>
          </div>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/BlueberryTartLogo.png"
                alt="Vercel Logo"
                
                width={50}
                height={50}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            
            src="/Platifylogo.png"
            alt="Next.js Logo"
            width={180}
            height={180}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://github.com/Thirstums/platify"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Github <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Platify Official Github
            </p>

            <Image
            
            src="/GithubLogo.png"
            alt="GitHub Logo"
            width={90}
            height={35}
            priority
          />
          </a>
        </div>
      </main>
    </>
  )
}

