import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";
import { createPlaylistByMatchingSongs, spotifyApi } from "./api/spotify";
import { getTrackList } from "./api/openai";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { getToken, refreshAccessToken } from "./api/auth/spotify-auth";

export default function PlaylistView() {
  return (
    <>
      <Head>
        <title>Platify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <a>
            <link href="/playlistview" />
            viewmage
          </a>
        </div>
      </main>
    </>
  );
}
